# --------------------------------------------------------------------------------------------#
#     A R C S I G H T   I N T E L L I G E N C E   S I N G L E   N O D E   T E M P L A T E     #
# --------------------------------------------------------------------------------------------#
#
# ArcSight Intelligence single node installation configuration
#
# This example configures all components required by Intelligence to be installed on a single node including Fusion, Transformation Hub and Database.
#
# Before using this example, you must do the following:
# - Replace the hostname "yourdomain-node.yourenterprise.net" (same value in multiple locations) with the correct values for your environment.
# - Replace "changeme" (for config parameter interset-elasticsearch-password)
# - Replace "changeme" (for config parameter interset-h2-password)
# - Set the values of arcmc-generator-id-start and arcmc-generator-id-end to form a valid Generator ID Range
#     Generator ID Range: set a valid range within [1-16383]. 
#     The difference between the values must be more than 100.
# 
# Key aspects of this configuration are:
# - Encryption: yes
# - Transformation Hub TLS Client Auth: yes
# - High Availability: no, since it is deployed on a single node
# - FIPS 140 mode: yes
#
# --------------------------------------------------------------------------------------------#
cluster:
  default-node-size: medium
  allow-worker-on-master: true
  enable-fips: true
  master-nodes:
    - hostname: yourdomain-node.yourenterprise.net
      username: root
      labels: [zk, kafka, th-processing, th-platform, fusion, intelligence, intelligence-spark, intelligence-datanode, intelligence-namenode]

suite:
  products: [fusion, transformationhub, intelligence]
  config-params:
    # Transformation Hub, defaults are commented
    # th-init-fips: true
    # th-init-noOfTopicPartitions: 6 # The ArcSight Platform Installer automatically sets th-arcsight-avro, mf-event-avro-enriched, and th-cef topic partition count to Number of Database Nodes * 24. Other topics use this parameter.
    # th-init-kafkaRetentionBytesForVertica: When the database is colocated with the Kubernetes cluster, the ArcSight Platform Installer automatically calculates this value.
    # th-init-kafkaRetentionBytes: When the database is colocated with the Kubernetes cluster, the ArcSight Platform Installer automatically calculates this value. 
    th-schema-registry-count: 1
    transform-processor-replicas: 1
    enrichment-processor1-replicas: 1
    # th-enrichment-processor-integrity-enabled: false
    routing-processor1-replicas: 0
    th-kafka-count: 1
    th-zookeeper-count: 1
    th-init-kafkaOffsetsTopicReplicationFactor: 1
    th-init-topicReplicationFactor: 1
    th-kafka-allow-plaintext: false
    th-init-client-auth: true
    # Intelligence
    # interset-hdfs-namenode: yourdomain-node.yourenterprise.net # The ArcSight Platform Installer automatically sets set worker node where "intelligence-namenode" label is present
    interset-logstash-instances: 1
    interset-h2-password: changeme
    interset-elasticsearch-password: changeme
    interset-elasticsearch-index-shards-count: 1
    interset-logstash-event-buffering: persisted
    interset-analytics-overhead-memory: 0.2
    # Fusion
    # Generator ID parameters are mandatory parameters.
    # Ensure that you set arcmc-generator-id-enable to true.
    arcmc-generator-id-start: 
    arcmc-generator-id-end: 
    arcmc-generator-id-enable: true

database:
  type: new
  ssl-enabled: true
  ssl-client-auth-enabled: true
  shard-count: 3
  s3:
    type: preconfigured
    server: yourdomain-s3-server.yourenterprise.net
    port: 443
    url: s3://bucket/folder
    access-key: S3_ACCESS_KEY
    tls-enabled: true
    region: your-s3-region
  nodes:
    - hostname: yourdomain-node.yourenterprise.net
      username: root
