cluster:
  default-node-size: medium
  master-api-ssl-port: 7443
  allow-worker-on-master: false
  enable-fips: false
  master-nodes:
    - hostname: master.advantageinc.org
      username: root
  worker-nodes:
   - hostname: worker1.advantageinc.org
     username: root
     labels: [zk, kafka, th-processing, th-platform, fusion, intelligence, intelligence-datanode, intelligence-namenode, intelligence-spark]
   - hostname: worker2.advantageinc.org
     username: root
     labels: [zk, kafka, th-processing, th-platform, fusion, intelligence, intelligence-datanode, intelligence-spark]
   - hostname: worker3.advantageinc.org
     username: root
     labels: [zk, kafka, th-processing, th-platform, fusion, intelligence, intelligence-datanode, intelligence-spark]


suite:
  products: [transformationhub, fusion, recon, esm, intelligence]
  config-params:
    th-schema-registry-count: 3
    transform-processor-replicas: 1
    routing-processor1-replicas: 0
    th-kafka-count: 3
    th-zookeeper-count: 3
    th-init-kafkaOffsetsTopicReplicationFactor: 1
    th-init-topicReplicationFactor: 1
    th-kafka-allow-plaintext: true
    th-init-client-auth: false
    arcmc-generator-id-start: 100
    arcmc-generator-id-end: 1000
    arcmc-generator-id-enable: true

    interset-elasticsearch-data-instances: 3
    interset-logstash-instances: 1
    interset-elasticsearch-password: changeme
    interset-h2-password: changeme
    interset-elasticsearch-index-shards-count: 1
    interset-logstash-event-buffering: persisted
    interset-analytics-overhead-memory: 0.2
    recon-enable: true


database:
  type: new
  ssl-enabled: false
  ssl-client-auth-enabled: false
  shard-count: 3
  s3:
    type: new
    server: minio.advantageinc.org
    port: 19001
    url: s3://events
    access-key: access_key
    # secret is "change_me"
    tls-enabled: false
    region: no-region-required
  nodes:
    - hostname: vertica.advantageinc.org
      username: root
  hardware:
    cpu: 8
    memory: 32
    disk: 200

nfs:
  node:
    hostname: nfs.advantageinc.org
    username: root
  type: new
  root-folder: /opt/arcsight-nfs
  uid: 1999
  gid: 1999

